### ISSUE TITLE
Crashes each time

### ISSUE THREAD

**Issue by Sxnpaiwin** [OldiumMC/oldium#1]
[01:34:02] [main/INFO]: Loading Minecraft 1.8.9 with Fabric Loader 0.15.6
[01:34:03] [ForkJoinPool-1-worker-1/WARN]: Mod oldium uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[01:34:03] [main/INFO]: Loading 46 mods:
	- axolotlclient 3.0.6+1.8.9
	   |-- axolotlclient-common 3.0.6
	   |-- axolotlclientconfig 2.1.13+1.8.9
	   |    |-- io_github_axolotlclient_axolotlclient-config_common_ 2.1.13
	   |    \-- legacyclientcommands 1.0.0
	   \-- search-in-resources 1.0.1
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- java 17
	- languagefix 1.0.0+1.8.9_to_1.12.2
	- legacy-fabric-api 1.10.2
	   |-- legacy-fabric-api-base 1.1.0+1.8.9+7c545fdbe239
	   |-- legacy-fabric-api-base-common 1.1.0+7c545fdbe692
	   |-- legacy-fabric-command-api-v1 1.0.1+052b5678db92
	   |-- legacy-fabric-command-api-v2 1.0.2+1.8.9+6c60a8d10039
	   |-- legacy-fabric-crash-report-info-v1 1.0.0+7c545fdb4992
	   |-- legacy-fabric-entity-events-v1 1.0.0+1.8.9+095a57590739
	   |-- legacy-fabric-entity-events-v1-common 1.0.0+095a57593e92
	   |-- legacy-fabric-gamerule-api-v1 1.0.0+7c545fdb4c92
	   |-- legacy-fabric-item-groups-v1 2.1.0+1.8.9+052b5678db39
	   |-- legacy-fabric-item-groups-v1-common 2.1.0+052b56784e92
	   |-- legacy-fabric-keybinding-api-v1 1.1.1+1.8.9+281301ea2839
	   |-- legacy-fabric-keybinding-api-v1-common 1.1.1+281301ea5992
	   |-- legacy-fabric-lifecycle-events-v1 1.1.0+1.8.9+052b5678f739
	   |-- legacy-fabric-lifecycle-events-v1-common 1.1.0+052b56787c92
	   |-- legacy-fabric-logger-api-v1 1.0.4+7c545fdb7292
	   |-- legacy-fabric-networking-api-v1 2.0.2+1.8.9+7c545fdb1839
	   |-- legacy-fabric-networking-api-v1-common 2.0.2+052b56786192
	   |-- legacy-fabric-permissions-api-v1 1.1.0+1.8.9+052b56787839
	   |-- legacy-fabric-permissions-api-v1-common 1.1.0+052b5678a792
	   |-- legacy-fabric-registry-sync-api-v1 2.2.0+1.8.9+7c545fdb6e39
	   |-- legacy-fabric-registry-sync-api-v1-common 2.2.0+1c4806cdcb92
	   |-- legacy-fabric-rendering-api-v1 1.0.0+1.8.9+7c545fdbba39
	   |-- legacy-fabric-rendering-api-v1-common 1.0.0+7c545fdb6992
	   |-- legacy-fabric-resource-loader-v1 2.2.1+1.8.9+7c545fdb4d39
	   \-- legacy-fabric-resource-loader-v1-common 2.2.1+052b5678f192
	- legacy-fixes 1.0.1
	- legacy-lwjgl3 1.1.7+1.8.9
	- legacyenhance 1.0.0
	   |-- com_velocitypowered_velocity-native 4.0.0-SNAPSHOT
	   \-- io_github_axolotlclient_axolotlclient-config_axolod6a22e2119cdc0 2.1.9
	- minecraft 1.8.9
	- modmenu 1.1.0
	- oldium ${version}
	- phosphor-legacy 0.1.3+1.8.9
	- realmsfix 2.0.4
[01:34:07] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Administrator/games/PrismLauncher-Windows-MSVC-Portable-8.0/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[01:34:14] [main/INFO]: Compatibility level set to JAVA_17
[01:34:18] [main/WARN]: Error loading class: net/minecraft/unmapped/C_8105098 (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_8105098)
[01:34:18] [main/WARN]: @Mixin target net.minecraft.unmapped.C_8105098 was not found legacy-lwjgl3.mixins.json:MixinMinecraftDrawVirtualCursor from mod legacy-lwjgl3
[01:34:18] [main/WARN]: Error loading class: net/minecraft/unmapped/C_8105098 (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_8105098)
[01:34:18] [main/WARN]: @Mixin target net.minecraft.unmapped.C_8105098 was not found legacy-lwjgl3.mixins.json:MixinMinecraftFixEarlyCrashNoReports from mod legacy-lwjgl3
[01:34:18] [main/WARN]: Error loading class: net/minecraft/unmapped/C_3020744 (java.lang.ClassNotFoundException: net/minecraft/unmapped/C_3020744)
[01:34:18] [main/WARN]: @Mixin target net.minecraft.unmapped.C_3020744 was not found legacy-lwjgl3.mixins.json:MixinScreenFixClipboard from mod legacy-lwjgl3
[01:34:19] [main/INFO]: resolved config: realmsfix-1.8.9.mixins.json
[01:34:21] [main/WARN]: @Redirect conflict. Skipping oldium.mixins.json:core.MixinMinecraft from mod oldium->@Redirect::oldium$noGarbageCollection()V with priority 1000, already redirected by axolotlclient.mixins.json:MinecraftClientMixin from mod axolotlclient->@Redirect::axolotlclient$noWorldGC()V with priority 1000
[01:34:21] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1600 failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.6.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1600 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1093) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:41) ~[minecraft-1.8.9-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1093) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:41) ~[minecraft-1.8.9-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 5 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector oldium$noGarbageCollection()V in oldium.mixins.json:core.MixinMinecraft from mod oldium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap oldium-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1093) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:41) ~[minecraft-1.8.9-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	... 5 more

**Comment by Decencies** [comment]
axolotlclient is incompatiable with oldium.

**Comment by Decencies** [comment]
Also note using oldium with legacy-fabric-api will also cause a crash

**Comment by TheRagg** [comment]
> axolotlclient is incompatiable with oldium.

Works fine for me. Although I noticed that chests aren't being rendered.
